repositories:
  remote:
    - https://repo1.maven.org/maven2

artifacts:
  idea_codestyle: au.com.stocksoftware.idea.codestyle:idea-codestyle:xml:1.17

  braincheck: org.realityforge.braincheck:braincheck-core:jar:1.31.0

  grim_annotations: org.realityforge.grim:grim-annotations:jar:0.09
  grim_processor: org.realityforge.grim:grim-processor:jar:0.09

  arez_core: org.realityforge.arez:arez-core:jar:0.209
  arez_processor: org.realityforge.arez:arez-processor:jar:0.209
  arez_testng: org.realityforge.arez:arez-extras-testng:jar:0.209

  shade_task: org.realityforge.ant.shade:ant-shade-task:jar:0.1

  javax_annotation: org.realityforge.javax.annotation:javax.annotation:jar:1.0.1
  # jetbrains_annotations required for arez atm
  jetbrains_annotations: org.realityforge.org.jetbrains.annotations:org.jetbrains.annotations:jar:1.7.0

  guiceyloops: org.realityforge.guiceyloops:guiceyloops:jar:0.113

  javapoet: com.squareup:javapoet:jar:1.13.0

  proton_core: org.realityforge.proton:proton-core:jar:0.64
  proton_qa: org.realityforge.proton:proton-qa:jar:0.64

  # GWT deps
  gwt_user: org.gwtproject:gwt-user:jar:2.11.0
  gwt_dev: org.gwtproject:gwt-dev:jar:2.11.0

  jsinterop_annotations: com.google.jsinterop:jsinterop-annotations:jar:2.0.0

  jsinterop_base: com.google.jsinterop:base:jar:1.0.0

  akasha: org.realityforge.akasha:akasha-gwt:jar:0.30

  javax_json: org.glassfish:javax.json:jar:1.1

  jdepend: guru.nidi:jdepend:jar:2.9.5

  # Mockito deps
  mockito: org.mockito:mockito-core:jar:4.5.1
  byte_buddy: net.bytebuddy:byte-buddy:jar:1.12.9
  objenesis: org.objenesis:objenesis:jar:3.2
