repositories:
  remote:
    - https://stocksoftware.jfrog.io/stocksoftware/maven2
    - https://repo.maven.apache.org/maven2
    - https://stocksoftware.jfrog.io/stocksoftware/staging

artifacts:
  idea_codestyle: au.com.stocksoftware.idea.codestyle:idea-codestyle:xml:1.17

  braincheck: org.realityforge.braincheck:braincheck:jar:1.29.0

  grim_annotations: org.realityforge.grim:grim-annotations:jar:0.04
  grim_processor: org.realityforge.grim:grim-processor:jar:0.04

  arez_core: org.realityforge.arez:arez-core:jar:0.192
  arez_processor: org.realityforge.arez:arez-processor:jar:0.192
  arez_testng: org.realityforge.arez.testng:arez-testng:jar:0.15

  shade_task: org.realityforge.ant.shade:ant-shade-task:jar:0.1

  javax_annotation: org.realityforge.javax.annotation:javax.annotation:jar:1.0.1
  # jetbrains_annotations required for arez atm
  jetbrains_annotations: org.realityforge.org.jetbrains.annotations:org.jetbrains.annotations:jar:1.7.0

  guiceyloops: org.realityforge.guiceyloops:guiceyloops:jar:0.106

  javapoet: com.squareup:javapoet:jar:1.13.0

  proton_core: org.realityforge.proton:proton-core:jar:0.51
  proton_qa: org.realityforge.proton:proton-qa:jar:0.51

  #test deps
  compile_testing: com.google.testing.compile:compile-testing:jar:0.18-rf
  guava: com.google.guava:guava:jar:27.1-jre
  guava_failureaccess: com.google.guava:failureaccess:jar:1.0.1
  truth: com.google.truth:truth:jar:0.45
  junit: junit:junit:jar:4.12
  hamcrest_core: org.hamcrest:hamcrest-core:jar:1.3

  # GWT deps
  gwt_user: com.google.gwt:gwt-user:jar:2.9.0
  gwt_dev: com.google.gwt:gwt-dev:jar:2.9.0

  jsinterop_annotations: com.google.jsinterop:jsinterop-annotations:jar:2.0.0

  jsinterop_base: com.google.jsinterop:base:jar:1.0.0

  elemental2_core: org.realityforge.com.google.elemental2:elemental2-core:jar:2.27
  elemental2_dom: org.realityforge.com.google.elemental2:elemental2-dom:jar:2.27
  elemental2_promise: org.realityforge.com.google.elemental2:elemental2-promise:jar:2.27
  elemental2_webstorage: org.realityforge.com.google.elemental2:elemental2-webstorage:jar:2.27

  javax_json: org.glassfish:javax.json:jar:1.1

  jdepend: guru.nidi:jdepend:jar:2.9.5

  testng: org.testng:testng:jar:6.11

  mockito: org.mockito:mockito-all:jar:1.10.19
